### ISSUE TITLE
Corregir navbar

### ISSUE THREAD

**Issue by ocean-girl** [sebapitta/MercadoLiebre#4]
Actualmente, aparece el menú hamburguesa junto con la barra de navegación. Ocultar el menú hamburguesa en la barra de navegación para la versión de Tablet y Desktop, y por otro lado, en la versión de mobile, ocultar la barra de navegación, mostrando solamente el menú hamburguesa.

**Comment by sebapitta** [comment]
issue has been resolved please check and confirm
