### ISSUE TITLE
Alinear logo con barra de búsqueda y leyenda "Compra en cuotas..."

### ISSUE THREAD

**Issue by ocean-girl** [sebapitta/MercadoLiebre#5]
Alinear logo con barra de búsqueda y leyenda "Compra en cuotas..." para que se visualice de la siguiente manera:

![image](https://user-images.githubusercontent.com/112780197/212081358-b634fbd8-a613-470f-bdcd-966dc5175025.png)

**Comment by sebapitta** [comment]
issue has been resolved please check and confirm
