### ISSUE TITLE
Alinear footer

### ISSUE THREAD

**Issue by ocean-girl** [sebapitta/MercadoLiebre#8]
Actualmente, en la versión desktop y tablet aparece el footer alineado en una sola columna, pero debe estar cada artículo en una misma fila, ver imagen:

![image](https://user-images.githubusercontent.com/112780197/212082724-f98ea4b7-3c1d-410e-af72-185ca147c9e8.png)

**Comment by sebapitta** [comment]
issue has been resolved please check and confirm
